[[environment]]
id = "local"
type = "local"

[environment.layout]
# root_dir = "/tmp/runtools_${USER}/env"

[environment.output]
# tail_buffer_size = 2097152

[[environment.output.storages]]
type = "file"
enabled = true
# dir = "~/.local/state/runtools/local/output"

[environment.retention]
max_runs_per_job = 100
max_runs_per_env = 1000

[environment.persistence]
type = "sqlite"
enabled = true
# database = "~/.local/share/runtools/main.db"
[environment.persistence.params]
# timeout = 5.0
# uri = false
